In [1]:
import numpy as np

In [2]:
a = np.random.rand(5)

In [3]:
a

array([0.17539379, 0.43186385, 0.23658313, 0.61239378, 0.23151351])

In [4]:
a.shape

(5,)

In [5]:
a.ndim

1

In [6]:
import time

In [12]:
a = np.random.rand(10000000)
b = np.random.rand(10000000)
start = time.time()
ans = np.dot(a,b)
end = time.time()

print("Vectorization Method take : ",(end-start)*1000," ms.")
print("Ans of multipication is : ",ans)
print("\n==============================================\n==============================================\n")
start = time.time()
ans = 0
for i in range(len(a)):
    ans += a[i]*b[i]
end = time.time()
print("Vectorization Method take : ",(end-start)*1000," ms.")
print("Ans of multipication is : ",ans)

Vectorization Method take :  20.944595336914062  ms.
Ans of multipication is :  2501026.587945422


Vectorization Method take :  8794.716835021973  ms.
Ans of multipication is :  2501026.5879456


In [16]:
a = np.array([[2,4,5]])
aT = np.transpose(a)
print("Shape of a : ",a.shape)
print("Shape of aT : ",aT.shape)

Shape of a :  (1, 3)
Shape of aT :  (3, 1)


In [19]:
a = np.array([[2,4,5]])
aT = a.T
print("Shape of a : ",a.shape)
print("Shape of aT : ",aT.shape)

Shape of a :  (1, 3)
Shape of aT :  (3, 1)


In [20]:
a = [
    [10,50,70],
    [50,70,90],
    [40,80,40]
]

In [22]:
a = np.array(a)
print("Array a is : \n",a)
print("=========================")
print("Shape of Array is : ",a.shape)

Array a is : 
 [[10 50 70]
 [50 70 90]
 [40 80 40]]
Shape of Array is :  (3, 3)


In [26]:
start = time.time()
dotA_A = np.dot(a,a)
end = time.time()
ti = (end-start)*1000

In [33]:
print("\nDot product is :\n",dotA_A)
print("Time Needed : ",ti,"ms")


Dot product is :
 [[ 5400  9600  8000]
 [ 7600 14600 13400]
 [ 6000 10800 11600]]
Time Needed :  52.887916564941406 ms


In [30]:
start = time.time()
ans = np.zeros((a.shape[0],a.shape[1]),dtype=np.int64)

for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        for k in range(a.shape[1]):
            ans[i,j] += a[i,k]*a[k,j]
end = time.time()
ti = (end-start)*1000

In [32]:
print("\nDot product is :\n",ans)
print("================================")
print("Time Needed : ",ti,"ms")


Dot product is :
 [[ 5400  9600  8000]
 [ 7600 14600 13400]
 [ 6000 10800 11600]]
Time Needed :  52.887916564941406 ms


In [46]:
ins_a = np.insert(a,3,[[10,20,30]],axis=1)

In [47]:
ins_a

array([[10, 50, 70, 10],
       [50, 70, 90, 20],
       [40, 80, 40, 30]])

In [49]:
ins_a + np.array([10,20,30,40]).reshape(1,4)

array([[ 20,  70, 100,  50],
       [ 60,  90, 120,  60],
       [ 50, 100,  70,  70]])

In [59]:
ins_a / ins_a.sum(axis=0).reshape(1,4)

array([[0.1       , 0.25      , 0.35      , 0.16666667],
       [0.5       , 0.35      , 0.45      , 0.33333333],
       [0.4       , 0.4       , 0.2       , 0.5       ]])